import { StubPage } from "@/components/admin/StubPage";

export const dynamic = "force-dynamic";

export default function ApprovalQueuePage() {
  return (
    <StubPage
      title="Approval Queue"
      description="The human-in-the-loop gate. Content generated by the Creative agent and actions proposed by the Governor agent wait here for your sign-off before they deploy."
    />
  );
}
