import { StubPage } from "@/components/admin/StubPage";
import { requireAdminContext } from "@/lib/auth/session";
import { isLifecycleEnabled } from "@/lib/lifecycle/flags";
import { ApprovalQueue } from "@/components/admin/approvals/ApprovalQueue";
import { ReviewHub } from "@/components/admin/review/ReviewHub";
import { isNavV2Phase2Enabled } from "@/lib/nav/flags";

export const dynamic = "force-dynamic";

/**
 * The human-in-the-loop gate. Today it holds the per-person AI lines for
 * lifecycle journeys (flag-gated); other agents' proposals join later.
 */
export default async function ApprovalQueuePage() {
  // Nav v2 phase 2: Review holds every waiting decision, not just AI lines.
  if (isNavV2Phase2Enabled()) return <ReviewHub />;
  const ctx = await requireAdminContext();
  if (!isLifecycleEnabled()) {
    return (
      <StubPage
        title="Approval Queue"
        description="The human-in-the-loop gate. Content generated by the Creative agent and actions proposed by the Governor agent wait here for your sign-off before they deploy."
      />
    );
  }
  return <ApprovalQueue canEdit={ctx.role === "admin"} />;
}
